---

- name: Include installation tasks
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags: ["install"]
  tags: ["install"]

- name: Copy systemd service
  ansible.builtin.template:
    src: "postfix-exporter.service.j2"
    dest: /etc/systemd/system/postfix-exporter.service
    owner: root
    group: root
    mode: 0644
  notify: Restart postfix exporter

- name: Enable and start service
  ansible.builtin.systemd:
    name: postfix-exporter.service
    state: started
    enabled: true
    daemon_reload: true
