---

- name: Verify
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Ensure exporter is running
      ansible.builtin.uri:
        url: "http://127.0.0.1:9907/metrics"
        return_content: true
      register: res

    - name: Ensure we got something
      ansible.builtin.assert:
        that: "'postfix_exporter_build_info' in res.content"
